# Generated by Django 4.2.10 on 2024-03-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=255)),
                ('applicant', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField()),
                ('past_days', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
