# Generated by Django 4.2.11 on 2024-03-18 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='final_approver',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='requests',
            name='users',
            field=models.ManyToManyField(related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
