# Generated by Django 4.2.11 on 2024-03-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_remove_requests_beneficiary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='users',
            new_name='assigned_users',
        ),
    ]
